### ISSUE TITLE
Go client API: Docs checklist

### ISSUE THREAD

**Issue by prrao87** [kuzudb/go-kuzu#4]
Just putting in a checklist for all places that the docs or descriptions need to be updated once this client is ready to be released:

- [x] Website: https://kuzudb.com/
- [x] GitHub repo [README](https://github.com/kuzudb/kuzu/blob/master/README.md)
- [x] Docs [installation guide](https://docs.kuzudb.com/installation/)
- [x] Docs [quick start](https://docs.kuzudb.com/get-started/#quick-start)
- [x] Docs [client API](https://docs.kuzudb.com/client-apis/)
- [x] Docs [system requirements](https://docs.kuzudb.com/system-requirements)
- [x] ~~Docs [developer guide](https://docs.kuzudb.com/developer-guide/#build-language-bindings) to build from source~~

**Comment by prrao87** [comment]
Completed.
